# HERE WE USE ALPINE BECAUSE IT IS LIGHT WEIGHT THAN OTHER LINUX DISTRIBUTION
FROM  node:24-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
#IN COPY WE PROVIDE 2 ARGUMENT ONE IS SOURCE ANOTHER IS DESTINATION
COPY . .
EXPOSE 8080
CMD ["npm","start"]


